# Generated by Django 4.1.6 on 2023-02-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_login_password_alter_login_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
